/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(async_word_extractor_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d0940cea8b8518b62418704b3b130ca4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radioteletype/async_word_extractor_bb.h>
// pydoc.h is automatically generated in the build directory
#include <async_word_extractor_bb_pydoc.h>

void bind_async_word_extractor_bb(py::module& m)
{

    using async_word_extractor_bb    = ::gr::radioteletype::async_word_extractor_bb;


    py::class_<async_word_extractor_bb, gr::block, gr::basic_block,
        std::shared_ptr<async_word_extractor_bb>>(m, "async_word_extractor_bb", D(async_word_extractor_bb))

        .def(py::init(&async_word_extractor_bb::make),
           py::arg("bits_per_word"),
           py::arg("sample_rate"),
           py::arg("bit_rate"),
           D(async_word_extractor_bb,make)
        )
        



        ;




}








