/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(baudot_encode_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(967cf659ba5a9d4bdaf42aec31cf47f4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radioteletype/baudot_encode_bb.h>
// pydoc.h is automatically generated in the build directory
#include <baudot_encode_bb_pydoc.h>

void bind_baudot_encode_bb(py::module& m)
{

    using baudot_encode_bb    = ::gr::radioteletype::baudot_encode_bb;


    py::class_<baudot_encode_bb, gr::block, gr::basic_block,
        std::shared_ptr<baudot_encode_bb>>(m, "baudot_encode_bb", D(baudot_encode_bb))

        .def(py::init(&baudot_encode_bb::make),
           D(baudot_encode_bb,make)
        )
        



        ;




}








