/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(baudot_decode_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d5a87b1c1bb85d024bbb8b3eb2e807e6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radioteletype/baudot_decode_bb.h>
// pydoc.h is automatically generated in the build directory
#include <baudot_decode_bb_pydoc.h>

void bind_baudot_decode_bb(py::module& m)
{

    using baudot_decode_bb    = ::gr::radioteletype::baudot_decode_bb;


    py::class_<baudot_decode_bb, gr::block, gr::basic_block,
        std::shared_ptr<baudot_decode_bb>>(m, "baudot_decode_bb", D(baudot_decode_bb))

        .def(py::init(&baudot_decode_bb::make),
           D(baudot_decode_bb,make)
        )
        



        ;




}








