/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(varicode_decode_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(445fc8364cdda2ac4177c8656ee7e944)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radioteletype/varicode_decode_bb.h>
// pydoc.h is automatically generated in the build directory
#include <varicode_decode_bb_pydoc.h>

void bind_varicode_decode_bb(py::module& m)
{

    using varicode_decode_bb    = ::gr::radioteletype::varicode_decode_bb;


    py::class_<varicode_decode_bb, gr::block, gr::basic_block,
        std::shared_ptr<varicode_decode_bb>>(m, "varicode_decode_bb", D(varicode_decode_bb))

        .def(py::init(&varicode_decode_bb::make),
           D(varicode_decode_bb,make)
        )
        



        ;




}








